# 지킬에 오신 걸 환영합니다!
#
# 이 구성 파일은 전체 블로그, 값에 영향을 미치는 설정을 위한 것입니다
# 한 번 설정하고 그 이후에는 거의 편집하지 않을 것으로 예상됩니다. 만약 찾는다면
# 당신 자신이 이 파일을 매우 자주 편집하고 지킬의 데이터 파일을 사용하는 것을 고려해 보십시오
# 자주 업데이트해야 하는 데이터에 대한 기능입니다.
#
# 기술적인 이유로 인해 이 파일은 사용 시 *NOT*가 자동으로 다시 로드됩니다
# 번들 exec 지킬 serve입니다. 이 파일을 변경하면 서버 프로세스를 다시 시작하십시오.

# 사이트 설정
# 이것들은 당신의 새로운 사이트를 개인화하기 위해 사용됩니다. HTML 파일을 보면,
# 다음을 통해 액세스하는 것을 볼 수 있습니다
# {{ site.title }}, {{ site.email }} 등을 통해 액세스되는 것을 볼 수 있습니다.
# 원하는 사용자 지정 변수를 생성할 수 있으며 이러한 변수에 액세스할 수 있습니다
# {{ site.myvariable }} 을(를) 통해 템플릿에 포함됩니다.
title: "월횽(Wolhyong) 블로그"
email: 'pjw7558@naver.com'
description: "다양한 분야를 경험하는 것을 좋아하는 그레이해커(Gray Hacker) 월횽입니다."
baseurl: "" # 사이트의 하위 경로(예: /https)
url: "https://wolhyong.github.io/" # 사이트의 기본 호스트 이름과 프로토콜(예: https://example.com )
twitter_username: 'jamigibbs'
github_username: 'wolhyong'
medium_username: 'blog.jamigibbs.com'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate-v2

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

### Phantom settings
footer_text: '© 2023 wolhyong'
admin_name: 'wolhyong'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
